filestore.cabal: refresh for ghc-8
GHC now requires explicit quantification.

Patch fixes the following build failure:
  [ 3 of 11] Compiling Data.FileStore.Types ( Data/FileStore/Types.hs, dist/build/Data/FileStore/Types.o )

  Data/FileStore/Types.hs:153:32: error:
    Not in scope: type variable ‘a’

Updated upper bounds for packages bundled with ghc-8.

Signed-off-by: Sergei Trofimovich <siarheit@google.com>